package it.polimi.client;

public enum Comando {
    
    MUOVE,
    ABILITA_SETTORI,
    SCEGLIE_AZIONE,
    SILENZIO_DICHIARATO,
    SETTORE_ANNUNCIATO,
    RISULTATO_ATTACCO,
    TURNO_FINITO,
    PESCA_CARTA,
    SETTORE_DA_ANNUNCIARE,
    CARTA_PESCATA,
    GIOCO_FINITO,
    MORTO,
    CONNESSIONE_PERSA;

}
